default:
  image: docker:24
  services:
    - docker:dind

variables:
  DOCKER_BUILDKIT: 1
  IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA

stages:
  - build

build and push:
  stage: build
  script:
    - docker buildx create --use
    - docker buildx inspect --bootstrap

    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx build --platform linux/amd64 -t $IMAGE_TAG . --push
